package com.misis.brs.Database;

enum MarkType {
    CLASS_PARTICIPATION_PART_1,
    CLASS_PARTICIPATION_PART_2,
    ONLINE_PART_1,
    ONLINE_PART_2,
    PROJECT_PART_1,
    PROJECT_PART_2,
    MIDTERM,
    FINAL_TEST
}
